import logging
from typing import Any, Dict, AsyncGenerator
from src.agents.base_v3 import BaseAgentV3
from src.tools.external.shopify_tool import shopify_tool

logger = logging.getLogger(__name__)

class ImageAgent(BaseAgentV3):
    def __init__(self):
        super().__init__(name="ImageAgent", model="flux-1-schnell")

    async def execute(self, task: str, context: Dict[str, Any] = None) -> AsyncGenerator[str, None]:
        logger.info(f"{self.name} generating image: {task}")
        # Call Replicate/HF for FLUX
        yield f"data: {self.name} generating image for '{task}'...\n\n"
        
        image_url = "https://example.com/generated.png" # Mocked for now
        yield f"data: [IMAGE] {image_url}\n\n"
        
        if context and context.get("publish_to_shopify"):
            yield f"data: {self.name} publishing product to Shopify...\n\n"
            res = await shopify_tool.create_product(
                title=f"Art: {task}",
                body_html=f"<p>Digital art generated by ARIA for {task}</p>",
                vendor="ARIA Engine",
                product_type="Digital Art",
                price="19.99",
                image_url=image_url
            )
            if res.get("success"):
                yield f"data: [SUCCESS] Product created: {res.get('shop_url')}\n\n"
            else:
                yield f"data: [ERROR] Shopify fail: {res.get('error')}\n\n"
