-- ============================================================
-- Aria V2 — Supabase Schema
-- Run in: Dashboard → SQL Editor → New query
-- ============================================================

-- Users
create table if not exists public.users (
  id          text primary key,
  email       text unique not null,
  name        text not null default '',
  picture     text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Conversations
create table if not exists public.conversations (
  id          uuid primary key default gen_random_uuid(),
  user_id     text not null references public.users(id) on delete cascade,
  created_at  timestamptz not null default now()
);
create index if not exists idx_conversations_user on public.conversations(user_id);

-- Messages
create table if not exists public.messages (
  id                uuid primary key default gen_random_uuid(),
  conversation_id   uuid not null references public.conversations(id) on delete cascade,
  role              text not null check (role in ('user', 'assistant')),
  content           text not null,
  created_at        timestamptz not null default now()
);
create index if not exists idx_messages_conv on public.messages(conversation_id);
create index if not exists idx_messages_fts  on public.messages using gin(to_tsvector('spanish', content));

-- Products
create table if not exists public.products (
  id            uuid primary key default gen_random_uuid(),
  user_id       text not null references public.users(id) on delete cascade,
  type          text not null check (type in ('course', 'ebook', 'bundle')),
  title         text not null,
  topic         text not null default '',
  description   text not null default '',
  price         numeric(10,2) not null default 0,
  status        text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  content_json  jsonb,
  created_at    timestamptz not null default now()
);
create index if not exists idx_products_user   on public.products(user_id);
create index if not exists idx_products_status on public.products(status);

-- Assets (images, videos, audio generated by Aria)
create table if not exists public.assets (
  id           uuid primary key default gen_random_uuid(),
  user_id      text not null references public.users(id) on delete cascade,
  type         text not null check (type in ('image', 'video', 'audio')),
  url          text not null,
  provider     text not null default '',
  prompt       text not null default '',
  product_id   uuid references public.products(id) on delete set null,
  created_at   timestamptz not null default now()
);
create index if not exists idx_assets_user on public.assets(user_id);
create index if not exists idx_assets_type on public.assets(type);

-- Persistent memory
create table if not exists public.memory (
  id          text primary key,
  user_id     text not null references public.users(id) on delete cascade,
  key         text not null,
  value       text not null,
  updated_at  timestamptz not null default now()
);
create index if not exists idx_memory_user on public.memory(user_id);

-- ── RLS ──────────────────────────────────────────────────────
alter table public.users         enable row level security;
alter table public.conversations  enable row level security;
alter table public.messages       enable row level security;
alter table public.products       enable row level security;
alter table public.assets         enable row level security;
alter table public.memory         enable row level security;

create policy "service_role_access" on public.users         for all using (true);
create policy "service_role_access" on public.conversations  for all using (true);
create policy "service_role_access" on public.messages       for all using (true);
create policy "service_role_access" on public.products       for all using (true);
create policy "service_role_access" on public.assets         for all using (true);
create policy "service_role_access" on public.memory         for all using (true);

-- ── Storage bucket ────────────────────────────────────────────
-- Run this separately in Dashboard → Storage → Create bucket
-- Name: assets | Public: true
-- Or via SQL:
-- insert into storage.buckets (id, name, public) values ('assets', 'assets', true) on conflict do nothing;
